---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: votingdb-pv-claim
  labels:
   app: db
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: aws-ebs-sc
  resources:
   requests:
     storage: 20Gi