---
apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: cluster-auth-k8s-arm-1-29-blueprint
spec:
  forProvider:
    region: us-west-2
    clusterName: arm-1-29-blueprint
  providerConfigRef:
    name: provider-config-aws-arm-1-29-blueprint
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: kubecontext-arm-1-29
