apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-admission-webhook
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: upstream
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: master
    path: apps/admission-webhook/upstream/overlays/cert-manager
  syncPolicy:
    automated:
      prune: true