apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-notebook-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: inline
    argocd.argoproj.io/sync-wave: "17"
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/arunvthangaraj/eks-blueprints-workloads.git
    targetRevision: main
    path: kubeflow-monitoring/upstream/notebook-controller
  syncPolicy:
    automated:
      prune: true