apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-oidc-authservice
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: upstream
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: master
    path: common/oidc-authservice/base
  syncPolicy:
    automated:
      prune: true