apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-profiles-and-kfam
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: upstream
    argocd.argoproj.io/sync-wave: "23"
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: master
    path: apps/profiles/upstream/overlays/kubeflow
  syncPolicy:
    automated:
      prune: true