{{ if .Values.spec.karpenterInstanceProfile }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: taint
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  consolidation:
    enabled: true
  #ttlSecondsAfterEmpty: 10 # mutual exclusive with consolitation
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: NotIn
      values:
        - a1
        - c1
        - c3
        - inf1
        - t3
        - t2
    # - key: karpenter.k8s.aws/instance-cpu
    #   operator: Lt
    #   values:
    #     - '33'

    # Default values
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    # - key: karpenter.k8s.aws/instance-category
    #   operator: In
    #   values:
    #     - c
    #     - m
    #     - r
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
        - '2'

    - key: 'kubernetes.io/arch'
      operator: In
      values: ['amd64']
    - key: karpenter.sh/capacity-type
      operator: In
      values: ['on-demand', 'spot']
      #values: ['on-demand']
  providerRef:
    name: karpenter-default

  ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;
  # Priority given to the provisioner when the scheduler considers which provisioner
  # to select. Higher weights indicate higher priority when comparing provisioners.
  # Specifying no weight is equivalent to specifying a weight of 0.
  weight: 1
  limits:
    resources:
      cpu: '40k'
      #cpu: '0'
  labels:
    billing-team: default
    team: platform
    type: karpenter
  taints:
    - key: karpenter
      value: 'true'
      effect: NoSchedule

  # Karpenter provides the ability to specify a few additional Kubelet args.
  # These are all optional and provide support for additional customization and use cases.
  kubeletConfiguration:
    #clusterDNS: ["10.0.1.100"]
    containerRuntime: containerd
    systemReserved:
      cpu: '1'
      memory: 5Gi
      ephemeral-storage: 2Gi
    #maxPods: 110
{{ end }}
