apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-burnham
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-burnham
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/shapirov103/argo-apps
    path: teams/team-burnham/prod
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}