apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp-deployment
  namespace: team-riker
spec:
  selector:
    matchLabels:
      app: skiapp
  replicas: 3
  template:
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
        - name: skiapp
          image: sharepointoscar/skiapp:v1
          env:
            - name: CLUSTER_NAME
              value: {{.Values.spec.clusterName}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector: # <- add nodeselector, toleration and spread constraitns
        team: default
        type: karpenter
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: skiapp          
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'                