apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-carmen
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-carmen
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/barisi/GeoLocationAPI
    path: templates
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true